webrecipes/cooking_recipes/urls.py
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.index, name='home'),
    path('about', views.about, name='about'),
    path('user/', include('user.urls', namespace='user')),
    path('crt_rec', views.crt_rec, name='crt_rec'),
    path('category/<str:ctg_slug>/', views.category_detail, name='category'),
    path('recipe/<str:rec_slug>/', views.recipe, name='recipe'),
    path('create_recipe/', views.create_recipe, name='create_recipe'),
    path('recipe/', views.recipe, name='recipe'),
    path('category_detail/', views.category_detail, name='category_detail'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webrecipes/user/urls.py
from django.urls import path, re_path

from .views import LoginUser, logout_user, RegisterUser

app_name = 'user'

urlpatterns = [
    path('login', LoginUser.as_view(), name='login'),
    path('logout', logout_user, name='logout'),
    path('register', RegisterUser.as_view(), name='register'),
]

webrecipes/webrecipes/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cooking_recipes.urls')),
]

webrecipes/cooking_recipes/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse
from autoslug import AutoSlugField


class Category(models.Model):
    name = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=255, unique=True, db_index=True, verbose_name='URL')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('category', kwargs={'ctg_slug': self.slug})


class Recipes(models.Model):
    recipe_id = models.AutoField(primary_key=True, verbose_name="Номер рецепта")
    title = models.CharField(max_length=100, verbose_name="Заголовок")
    slug = AutoSlugField(populate_from='title', max_length=255, unique=True, db_index=True, verbose_name='URL')
    recipe_description = models.TextField(max_length=255, blank=True, verbose_name="Краткое описание")
    img = models.ImageField(upload_to="photos/%Y/%m/%d/", verbose_name='Изображение')
    time_created = models.DateTimeField(auto_now_add=True, verbose_name='Время создания')
    time_update = models.DateTimeField(auto_now=True, verbose_name='Время редактирования')

    ctg = models.ForeignKey(Category, on_delete=models.CASCADE)
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('recipe', kwargs={'rec_slug': self.slug})


class Steps(models.Model):
    step_id = models.AutoField(primary_key=True, verbose_name="Номер шага")
    step_description = models.TextField(max_length=255, blank=True, verbose_name="Шаг рецепта")

    recipe = models.ForeignKey(Recipes, on_delete=models.CASCADE)
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)


class Comments(models.Model):
    comment_id = models.AutoField(primary_key=True, verbose_name="Номер комментария")
    comment_text = models.TextField(max_length=255, blank=False, verbose_name="Комментарий")

    user_id = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    recipe_id = models.ForeignKey(Recipes, on_delete=models.CASCADE)

webrecipes/cooking_recipes/forms.py
from django import forms

from .models import Recipes, Steps, Category, Comments


# class RecipeForm(forms.ModelForm):
#     class Meta:
#         model = Recipes
#         fields = ['title', 'recipe_description', 'img', 'ctg']
#
#     def __init__(self, *args, **kwargs):
#         super().__init__(*args, **kwargs)
#         self.fields['title'].widget.attrs.update({'class': 'form-control py-4'})
#         self.fields['recipe_description'].widget.attrs.update({'class': 'form-control py-4'})
#         self.fields['img'].widget.attrs.update({'class': 'form-control py-4', 'size': (300, 200)})
#         self.fields['ctg'].widget.attrs.update({'class': 'form-control py-4'})

class RecipeForm(forms.ModelForm):
    title = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control py-4'}))
    description = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control py-4'}))
    image = forms.ImageField(widget=forms.FileInput(attrs={'class': 'form-control py-4', 'size': (300, 200)}))
    ctg = forms.ModelChoiceField(queryset=Category.objects.all(),
                                 widget=forms.Select(attrs={'class': 'form-control py-4'}))

    class Meta:
        model = Recipes
        fields = ['title', 'description', 'image', 'ctg']


class StepForm(forms.ModelForm):
    step = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control py-4'}))

    class Meta:
        model = Steps
        fields = ['step_description']


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comments
        fields = ['comment_text']

webrecipes/cooking_recipes/views.py
from django.shortcuts import render, get_object_or_404, redirect

from .forms import CommentForm
from .models import Category, Recipes, Steps


def index(request):
    recipes = Recipes.objects.all()
    categories = Category.objects.all()
    context = {'categories': categories, 'recipes': recipes}

    return render(request, 'cooking_recipes/index.html', context)


def about(request):
    return render(request, 'cooking_recipes/about.html')


def login(request):
    return render(request, 'cooking_recipes/login.html')


def crt_rec(request):
    categories = Category.objects.all()
    context = {'categories': categories}

    return render(request, 'cooking_recipes/crt_rec.html', context)


def category_detail(request, ctg_slug):
    category = get_object_or_404(Category, slug=ctg_slug)
    recipes = Recipes.objects.filter(ctg=category)
    context = {'category': category, 'recipes': recipes}
    return render(request, 'cooking_recipes/category_detail.html',
                  context)  # дапісаць файл для атабражэння рэцэптаў, па выбранай катэгорыі


def create_recipe(request):
    if request.method == 'POST':
        title = request.POST.get('recipe_name')
        description = request.POST.get('recipe_description')
        image = request.FILES.get('recipe_image')
        ctg = request.POST.get('recipe_category')
        category = Category.objects.get(name=ctg)
        recipe = Recipes.objects.create(
            title=title,
            recipe_description=description,
            img=image,
            ctg=category,
            user_id=request.user.id
        )
        recipe.save()
        recipe_id = recipe.pk  # или recipe.id
        for key, value in request.POST.items():
            if key.startswith('step'):
                step_description = value
                step = Steps.objects.create(
                    step_description=step_description,
                    recipe_id=recipe_id,
                    user_id=request.user.id
                )
        return redirect('home')
    else:
        return render(request, 'cooking_recipes/crt_rec.html')

# def create_recipe(request):
#     if request.method == 'POST':
#         form = RecipeForm(request.POST, request.FILES)
#         if form.is_valid():
#             recipe = form.save(commit=False)
#             recipe.user = request.user
#             recipe.save()
#             recipe_id = recipe.pk
#             for key, value in request.POST.items():
#                 if key.startswith('step'):
#                     step_description = value
#                     step = Steps.objects.create(
#                         step_description=step_description,
#                         recipe_id=recipe_id,
#                         user_id=request.user.id
#                     )
#             return redirect('home')
#     else:
#         form = RecipeForm()
#     return render(request, 'cooking_recipes/crt_rec.html', {'form': form})


# def recipe(request, rec_slug):
#     recipe = get_object_or_404(Recipes, slug=rec_slug)
#     form = CommentForm()
#     context = {'recipe': recipe, 'form': form}
#     return render(request, 'cooking_recipes/recipe.html', context)

def recipe(request, rec_slug):
    recipe = get_object_or_404(Recipes, slug=rec_slug)
    # Если это POST-запрос, обрабатываем данные из формы
    if request.method == 'POST':
        form = CommentForm(request.POST)
        # Проверяем валидность формы
        if form.is_valid():
            # Связываем комментарий с рецептом и пользователем
            comment = form.save(commit=False)
            comment.recipe_id = recipe
            comment.user_id = request.user
            # Сохраняем комментарий в базу данных
            comment.save()
            # Перенаправляем на ту же страницу
            return redirect('recipe', rec_slug=rec_slug)
    # Если это не POST-запрос, создаем пустую форму
    else:
        form = CommentForm()
    # Получаем список всех комментариев к рецепту
    comments = recipe.comments_set.all()
    # Передаем контекст в шаблон
    return render(request, 'cooking_recipes/recipe.html', {'recipe': recipe, 'form': form, 'comments': comments})

webrecipes/cooking_recipes/templates/cooking_recipes/about.html
{% extends 'cooking_recipes/base.html' %}

{% block title %}
О нас
{% endblock title %}

{% block content %}
    <h1>О нас</h1>
    <p>Страничка о нас</p>
{% endblock content %}

webrecipes/cooking_recipes/templates/cooking_recipes/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock title%}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css">
    <link type="text/css" href="{% static 'cooking_recipes/css/styles.css' %}" rel="stylesheet"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <div class="d-flex justify-content-between d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white">
        <h5 class="my-0 mr-md-auto front-weight-normal">culMaster</h5>
        <nav class="my-2 my-md-0 mr-md-3">
            <a class="p-2 text-dark" href="{% url 'home' %}">Главная</a>
            <a class="p-2 text-dark" href="{% url 'about' %}">О нас</a>
        </nav>
        {% if user.is_authenticated %}
        <a class="btn btn-outline-primary" href="{% url 'user:logout' %}">Выйти</a>
        {% else %}
        <a class="btn btn-outline-primary" href="{% url 'user:login' %}">Войти</a>
        {% endif %}

    </div>
</head>
<body>
<div class="container">
    {% block content %}
    {% endblock content%}
</div>
</body>
</html>

webrecipes/cooking_recipes/templates/cooking_recipes/category_detail.html
{% extends 'cooking_recipes/base.html' %}

{% block title %}
{{ category.name }}
{% endblock title %}

{% block content %}
<style>
h1 {
  text-align: center; 
}

    .list-recipes {
  list-style: none;
}

.recipe-panel {
  display: flex;
  justify-content: space-between;
  align-items: flex-start; /* Выравниваем элементы по верхнему краю */
}

.link-read-recipe {
  background-color: darkblue;
  color: white;
  border: none;
  cursor: pointer;
  margin-bottom: 1px;
  vertical-align: bottom;
}

li {
  clear: both; /* Отменяем обтекание */
  border-top: 1px solid gray;
  padding-top: 20px;
}

.info {
  display: flex; /* Делаем элемент флекс-контейнером */
  flex-direction: column; /* Устанавливаем вертикальное направление */
  justify-content: space-between; /* Распределяем элементы по вертикали */
  margin-left: 0; /* Убираем отступ слева */
}
</style>
    <h1>{{ category.name }} </h1>
    <ul class="list-recipes">
        {% for r in category.recipes_set.all %} <!-- Выводим все рецепты, принадлежащие данной категории -->
        <li>

            {% if r.img %}
            <img class="img-recipe-left thumb" src="{{r.img.url}}" width="300" height="200" style="float: left;">
            {% endif%}
            <div class="recipe-panel">
                <h2>{{r.title}}</h2>
                <div>
                  <p class="first">Категория: {{r.ctg}}</p>
                  <p class="last">Дата: {{r.time_update|date:"d-m-Y H:i:s"}}</p>
                </div>
            </div>
            <div class="info">
                {% autoescape on %}
                {{r.recipe_description|linebreaks|truncatewords:50}}
                {% endautoescape %}
                <button class="link-read-recipe" onclick="window.location.href = '{{ r.get_absolute_url }}';">Подробнее</button>
            </div>
            <div class="clear"></div>
        </li>
        {% endfor %}
    </ul>
{% endblock %}

webrecipes/cooking_recipes/templates/cooking_recipes/crt_rec.html
{% extends 'cooking_recipes/base.html' %}
{% load static %}

{% block title %}
Создание рецепта
{% endblock title %}

{% block content %}

<style>
    body {
        font-family: Arial, sans-serif;
        background-color: #f9f9f9;
        margin: 0;
        padding: 0;
    }
    .container {
        max-width: 800px;
        margin: 0 auto;
        padding: 20px;
        background-color: #ffffff;
        border-radius: 10px;
        box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
    }
    label {
        color: #8B0000;
        font-weight: bold;
    }
    input[type="text"],
    textarea {
        width: 100%;
        padding: 10px;
        margin-bottom: 20px;
        border: 1px solid #ccc;
        border-radius: 5px;
        font-size: 16px;
    }
    button {
        background-color: #8B0000;
        color: white;
        border: none;
        border-radius: 5px;
        padding: 10px 20px;
        font-size: 16px;
        cursor: pointer;
    }
    button:hover {
        background-color: #6A0000;
    }
</style>
<form method="POST" action="{% url 'create_recipe' %}" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="container">
        <h1 style="color: #8B0000;">Рецепт</h1>
        <label for="recipe_name">Название рецепта:</label>
        <input type="text" id="recipe_name" name="recipe_name">
        <label for="recipe_description">Краткое описание рецепта:</label>
        <textarea id="recipe_description" name="recipe_description"></textarea>
        <label for="recipe_image" style="display: block;">Фото:</label>
        <input type="file" id="recipe_image" name="recipe_image" style="display: block;">
        <label for="recipe_category" style="display: block;">Категория рецепта:</label>
        <select id="recipe_category" name="recipe_category" style="display: block; width: 200px;">
            {% for category in categories %}
                <option value="{{category}}">{{category.name}}</option>
            {% endfor %}
        </select>
        <label for="step1">Шаги:</label>
        <div id="steps-container">
            <textarea id="step1" name="step1"></textarea>
        </div>
        <button type="button" onclick="addStep()">Добавить шаг</button>
        <button type="submit">Создать</button>
    </div>
</form>

<script>
  function addStep() {
    const container = document.getElementById('steps-container');
    const lastStepInput = container.querySelector('textarea[name^="step"]:last-of-type');
    const newStepInput = lastStepInput.cloneNode(true);
    const stepNumber = parseInt(newStepInput.name.match(/\d+/)[0]) + 1;
    newStepInput.name = `step${stepNumber}`;
    newStepInput.value = ''; // Clear the cloned input
    container.appendChild(newStepInput);
}
</script>

{% endblock content %}

webrecipes/cooking_recipes/templates/cooking_recipes/index.html
{% extends 'cooking_recipes/base.html' %}
{% load static %}

{% block title %}
Главная страница
{% endblock title %}

{% block content %}

    <div class="d-flex justify-content-between align-items-center">
      <form class="form-inline my-2 my-lg-0 flex-grow-1" onsubmit="return false;">
        <div class="input-group w-100">
          <input class="form-control" type="search" placeholder="Поиск" aria-label="Поиск" onkeydown="if (event.keyCode == 13) { this.form.submit(); }">
        </div>
      </form>
      <button class="btn btn-outline-secondary btn-block" type="button">Найти</button>
    </div>

    <div class="container">
        <ul style="list-style-type: none; margin: 0; padding: 0; overflow: hidden; padding-top: 10px;">
            {% for category in categories %}
            <li style="float: left; margin-right: 10px;"><a href="{{ category.get_absolute_url }}" style="display: block; color: #000; text-align: center; padding: 14px 16px; text-decoration: none; border: 1px solid #000; border-radius: 10px; transition: background-color 0.3s ease; }">{{ category.name }}</a></li>
            {% endfor %}
        </ul>
    </div>

    <style>
        a:hover {
            background-color: #ddd;
            color: black;
        }
    </style>

    <div class="input-group-append">
        <a class="btn btn-outline-success btn-block" href="{% url 'crt_rec' %}">Создать рецепт</a>
    </div>

    <img class="main_img" src="{% static 'cooking_recipes/images/main2.jpg' %}" alt="Описание изображения"
    width="1200" height="700">

<!--    <ul class="list-recipes">-->
<!--        {% for r in recipes %}-->
<!--                <li><div class="recipe-panel">-->
<!--        <p class="first">Категория: {{r.ctg}}</p>-->
<!--        <p class="last">Дата: {{r.time_update|date:"d-m-Y H:i:s"}}</p>-->
<!--    </div>-->

<!--    {% if r.img %}-->
<!--        <p><img class="img-recipe-left thumb" src="{{r.img.url}}"></p>-->
<!--    {% endif%}-->

<!--                    <h2>{{r.title}}</h2>-->
<!--        {% autoescape on %}-->
<!--        {{r.recipe_description|linebreaks|truncatewords:50}}-->
<!--        {% endautoescape %}-->
<!--                <div class="clear"></div>-->
<!--                <p class="link-read-recipe"><a href="{{ r.get_absolute_url }}">Подробнее</a></p>-->
<!--                </li>-->
<!--        {% endfor %}-->
<!--    </ul>-->

<style>
    .list-recipes {
  list-style: none;
}

.recipe-panel {
  display: flex;
  justify-content: space-between;
  align-items: flex-start; /* Выравниваем элементы по верхнему краю */
}

.link-read-recipe {
  background-color: darkblue;
  color: white;
  border: none;
  cursor: pointer;
  margin-bottom: 1px;
  vertical-align: bottom;
}

li {
  clear: both; /* Отменяем обтекание */
  border-top: 1px solid gray;
  padding-top: 20px;
}

.info {
  display: flex; /* Делаем элемент флекс-контейнером */
  flex-direction: column; /* Устанавливаем вертикальное направление */
  justify-content: space-between; /* Распределяем элементы по вертикали */
  margin-left: 0; /* Убираем отступ слева */
}
</style>

    <ul class="list-recipes">
        {% for r in recipes %}
        <li>

            {% if r.img %}
            <img class="img-recipe-left thumb" src="{{r.img.url}}" width="300" height="200" style="float: left;">
            {% endif%}
            <div class="recipe-panel">
                <h2>{{r.title}}</h2>
                <div>
                  <p class="first">Категория: {{r.ctg}}</p>
                  <p class="last">Дата: {{r.time_update|date:"d-m-Y H:i:s"}}</p>
                </div>
            </div>
            <div class="info">
                {% autoescape on %}
                {{r.recipe_description|linebreaks|truncatewords:50}}
                {% endautoescape %}
                <button class="link-read-recipe" onclick="window.location.href = '{{ r.get_absolute_url }}';">Подробнее</button>
            </div>
            <div class="clear"></div>
        </li>
        {% endfor %}
    </ul>

{% endblock content %}

webrecipes/cooking_recipes/templates/cooking_recipes/recipe.html
{% extends 'cooking_recipes/base.html' %}
{% block content %}

<style>
    h1 {
    text-align: center; /* Выравниваем текст по центру */
}

    textarea {
    height: 100px; /* Устанавливаем высоту поля в 100 пикселей */
}

    .button-edit {
  background-color: white; /* Устанавливаем белый цвет фона */
  border-color: blue; /* Устанавливаем синий цвет границы */
  color: blue; /* Устанавливаем синий цвет текста */
}

/* Стиль для кнопки Редактировать при наведении */
.button-edit:hover {
  background-color: blue; /* Устанавливаем синий цвет фона */
  border-color: white; /* Устанавливаем белый цвет границы */
  color: white; /* Устанавливаем белый цвет текста */
}

/* Стиль для кнопки Удалить */
.button-delete {
  background-color: white; /* Устанавливаем белый цвет фона */
  border-color: red; /* Устанавливаем красный цвет границы */
  color: red; /* Устанавливаем красный цвет текста */
}

/* Стиль для кнопки Удалить при наведении */
.button-delete:hover {
  background-color: red; /* Устанавливаем красный цвет фона */
  border-color: white; /* Устанавливаем белый цвет границы */
  color: white; /* Устанавливаем белый цвет текста */
}

/* Стиль для кнопки Отправить */
.button-submit {
  background-color: white; /* Устанавливаем белый цвет фона */
  border-color: black; /* Устанавливаем черный цвет границы */
  color: black; /* Устанавливаем черный цвет текста */
}

/* Стиль для кнопки Отправить при наведении */
.button-submit:hover {
  background-color: black; /* Устанавливаем черный цвет фона */
  border-color: white; /* Устанавливаем белый цвет границы */
  color: white; /* Устанавливаем белый цвет текста */
}

textarea {
  width: 80%;
  height: 50px;
  max-height: 50px;
}
</style>

<div class="container">
    <p><small class="text-muted">Создано {{ recipe.time_created|date:"d.m.Y в H:i" }}</small></p>
    <div class="buttons">
        <button type="button" class="button-edit">Редактировать</button>
        <button type="button" class="button-delete">Удалить</button>
    </div>
    <h1>{{ recipe.title }}</h1>
    {% if recipe.img %}
        <img src="{{ recipe.img.url }}" alt="{{ recipe.title }}" class="img-fluid">
    {% endif%}
    <p>{{ recipe.recipe_description }}</p>

    {% for step in recipe.steps_set.all %}
    <div class="step">
        <h3>Шаг {{ forloop.counter }}</h3>
        <p>{{ step.step_description }}</p>
    </div>
    {% endfor %}
    <form method="post">
        {% csrf_token %}
        {{ form }}
        <button  type="submit" class="button-submit">Отправить</button>
    </form>
    {% for comment in comments %}
    <div class="comment">
        <p><strong>{{ comment.user_id.username }}</strong></p>
        <p>{{ comment.comment_text }}</p>
    </div>
    {% endfor %}


</div>
{% endblock %}