webrecipes/cooking_recipes/urls.py
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.index, name='home'),
    path('about', views.about, name='about'),
    path('user/', include('user.urls', namespace='user')),
    path('crt_rec', views.crt_rec, name='crt_rec'),
    path('category/<str:ctg_slug>/', views.category_detail, name='category'),
    path('recipe/<str:rec_slug>/', views.recipe, name='recipe'),
    path('create_recipe/', views.create_recipe, name='create_recipe'),
    path('recipe/', views.recipe, name='recipe'),
    path('category_detail/', views.category_detail, name='category_detail'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webrecipes/user/urls.py
from django.urls import path, re_path

from .views import LoginUser, logout_user, RegisterUser

app_name = 'user'

urlpatterns = [
    path('login', LoginUser.as_view(), name='login'),
    path('logout', logout_user, name='logout'),
    path('register', RegisterUser.as_view(), name='register'),
]

webrecipes/webrecipes/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cooking_recipes.urls')),
]

webrecipes/cooking_recipes/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse
from autoslug import AutoSlugField


class Category(models.Model):
    name = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=255, unique=True, db_index=True, verbose_name='URL')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('category', kwargs={'ctg_slug': self.slug})


class Recipes(models.Model):
    recipe_id = models.AutoField(primary_key=True, verbose_name="Номер рецепта")
    title = models.CharField(max_length=100, verbose_name="Заголовок")
    slug = AutoSlugField(populate_from='title', max_length=255, unique=True, db_index=True, verbose_name='URL')
    recipe_description = models.TextField(max_length=255, blank=True, verbose_name="Краткое описание")
    img = models.ImageField(upload_to="photos/%Y/%m/%d/", verbose_name='Изображение')
    time_created = models.DateTimeField(auto_now_add=True, verbose_name='Время создания')
    time_update = models.DateTimeField(auto_now=True, verbose_name='Время редактирования')

    ctg = models.ForeignKey(Category, on_delete=models.CASCADE)
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('recipe', kwargs={'rec_slug': self.slug})


class Steps(models.Model):
    step_id = models.AutoField(primary_key=True, verbose_name="Номер шага")
    step_description = models.TextField(max_length=255, blank=True, verbose_name="Шаг рецепта")

    recipe = models.ForeignKey(Recipes, on_delete=models.CASCADE)
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)


class Comments(models.Model):
    comment_id = models.AutoField(primary_key=True, verbose_name="Номер комментария")
    comment_text = models.TextField(max_length=255, blank=False, verbose_name="Комментарий")

    user_id = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    recipe_id = models.ForeignKey(Recipes, on_delete=models.CASCADE)

webrecipes/user/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser, models.Model):
    is_admin = models.BooleanField(default=False, blank=True)


# class Users(AbstractUser):
#     user_id = models.AutoField(primary_key=True, verbose_name="Номер пользователя")
#     username = models.CharField(max_length=255, verbose_name="Имя")
#     email = models.EmailField(max_length=255, verbose_name="Эл. Почта")
#     password = models.CharField(max_length=255, verbose_name="Пароль")
#     user_permissions = models.ManyToManyField(
#         'auth.Permission',
#         related_name='users_permissions',
#         blank=True,
#     )
#     groups = models.ManyToManyField(
#         'auth.Group',
#         related_name='users_groups',
#         blank=True,
#     )
#
#     def __str__(self):
#         return self.username

webrecipes/cooking_recipes/forms.py
from django import forms

from .models import Recipes, Steps, Category, Comments


# class RecipeForm(forms.ModelForm):
#     class Meta:
#         model = Recipes
#         fields = ['title', 'recipe_description', 'img', 'ctg']
#
#     def __init__(self, *args, **kwargs):
#         super().__init__(*args, **kwargs)
#         self.fields['title'].widget.attrs.update({'class': 'form-control py-4'})
#         self.fields['recipe_description'].widget.attrs.update({'class': 'form-control py-4'})
#         self.fields['img'].widget.attrs.update({'class': 'form-control py-4', 'size': (300, 200)})
#         self.fields['ctg'].widget.attrs.update({'class': 'form-control py-4'})

class RecipeForm(forms.ModelForm):
    title = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control py-4'}))
    description = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control py-4'}))
    image = forms.ImageField(widget=forms.FileInput(attrs={'class': 'form-control py-4', 'size': (300, 200)}))
    ctg = forms.ModelChoiceField(queryset=Category.objects.all(),
                                 widget=forms.Select(attrs={'class': 'form-control py-4'}))

    class Meta:
        model = Recipes
        fields = ['title', 'description', 'image', 'ctg']


class StepForm(forms.ModelForm):
    step = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control py-4'}))

    class Meta:
        model = Steps
        fields = ['step_description']


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comments
        fields = ['comment_text']

webrecipes/user/forms.py
from django import forms
from django.contrib.auth import authenticate
from django.contrib.auth.forms import UserChangeForm, UserCreationForm, AuthenticationForm

from .models import User


class UserProfileForm(UserChangeForm):
    username = forms.CharField(required=False, widget=forms.TextInput(attrs={'class': 'form-control py-4'}))
    email = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control py-4', 'readonly': True}))

    class Meta:
        model = User
        fields = ['username', 'email']


class RegisterUserForm(UserCreationForm):
    username = forms.CharField(label='Логин', widget=forms.TextInput(attrs={'class': 'form-input'}))
    email = forms.EmailField(label='Email', widget=forms.EmailInput(attrs={'class': 'form-input'}))
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    is_admin = forms.BooleanField(label='Администратор?', required=False,
                                  widget=forms.CheckboxInput(attrs={'class': 'form-input'}))

    class Meta:
        model = User
        fields = ('username', 'email', 'password', 'is_admin')


class LoginUserForm(AuthenticationForm):
    username = forms.CharField(label='Логин', widget=forms.TextInput(attrs={'class': 'form-input'}))
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-input'}))

    def clean(self):
        cleaned_data = super().clean()
        username = cleaned_data.get('username')
        password = cleaned_data.get('password')

        user = authenticate(username=username, password=password)
        if not user:
            raise forms.ValidationError("Неправильный логин или пароль")

        return cleaned_data

# class RegistrationForm(forms.ModelForm):
#     class Meta:
#         model = Users
#         fields = ['username', 'email', 'password']
#         widgets = {
#             'password': forms.PasswordInput()
#         }
#
#
# class LoginForm(forms.ModelForm):
#     username = forms.CharField(label='Логін')
#     password = forms.CharField(label='Пароль', widget=forms.PasswordInput)
#
#     class Meta:
#         model = Users
#         fields = ['username', 'password']
#
#     def clean(self):
#         cleaned_data = super().clean()
#         username = cleaned_data.get('username')
#         password = cleaned_data.get('password')
#
#         user = authenticate(username=username, password=password)
#         if not user:
#             raise forms.ValidationError("Неправильный логин или пароль")
#
#         return cleaned_data

webrecipes/cooking_recipes/views.py
from django.shortcuts import render, get_object_or_404, redirect

from .forms import CommentForm
from .models import Category, Recipes, Steps


def index(request):
    recipes = Recipes.objects.all()
    categories = Category.objects.all()
    context = {'categories': categories, 'recipes': recipes}

    return render(request, 'cooking_recipes/index.html', context)


def about(request):
    return render(request, 'cooking_recipes/about.html')


def login(request):
    return render(request, 'cooking_recipes/login.html')


def crt_rec(request):
    categories = Category.objects.all()
    context = {'categories': categories}

    return render(request, 'cooking_recipes/crt_rec.html', context)


def category_detail(request, ctg_slug):
    category = get_object_or_404(Category, slug=ctg_slug)
    recipes = Recipes.objects.filter(ctg=category)
    context = {'category': category, 'recipes': recipes}
    return render(request, 'cooking_recipes/category_detail.html',
                  context)  # дапісаць файл для атабражэння рэцэптаў, па выбранай катэгорыі


def create_recipe(request):
    if request.method == 'POST':
        title = request.POST.get('recipe_name')
        description = request.POST.get('recipe_description')
        image = request.FILES.get('recipe_image')
        ctg = request.POST.get('recipe_category')
        category = Category.objects.get(name=ctg)
        recipe = Recipes.objects.create(
            title=title,
            recipe_description=description,
            img=image,
            ctg=category,
            user_id=request.user.id
        )
        recipe.save()
        recipe_id = recipe.pk  # или recipe.id
        for key, value in request.POST.items():
            if key.startswith('step'):
                step_description = value
                step = Steps.objects.create(
                    step_description=step_description,
                    recipe_id=recipe_id,
                    user_id=request.user.id
                )
        return redirect('home')
    else:
        return render(request, 'cooking_recipes/crt_rec.html')

# def create_recipe(request):
#     if request.method == 'POST':
#         form = RecipeForm(request.POST, request.FILES)
#         if form.is_valid():
#             recipe = form.save(commit=False)
#             recipe.user = request.user
#             recipe.save()
#             recipe_id = recipe.pk
#             for key, value in request.POST.items():
#                 if key.startswith('step'):
#                     step_description = value
#                     step = Steps.objects.create(
#                         step_description=step_description,
#                         recipe_id=recipe_id,
#                         user_id=request.user.id
#                     )
#             return redirect('home')
#     else:
#         form = RecipeForm()
#     return render(request, 'cooking_recipes/crt_rec.html', {'form': form})


# def recipe(request, rec_slug):
#     recipe = get_object_or_404(Recipes, slug=rec_slug)
#     form = CommentForm()
#     context = {'recipe': recipe, 'form': form}
#     return render(request, 'cooking_recipes/recipe.html', context)

def recipe(request, rec_slug):
    recipe = get_object_or_404(Recipes, slug=rec_slug)
    # Если это POST-запрос, обрабатываем данные из формы
    if request.method == 'POST':
        form = CommentForm(request.POST)
        # Проверяем валидность формы
        if form.is_valid():
            # Связываем комментарий с рецептом и пользователем
            comment = form.save(commit=False)
            comment.recipe_id = recipe
            comment.user_id = request.user
            # Сохраняем комментарий в базу данных
            comment.save()
            # Перенаправляем на ту же страницу
            return redirect('recipe', rec_slug=rec_slug)
    # Если это не POST-запрос, создаем пустую форму
    else:
        form = CommentForm()
    # Получаем список всех комментариев к рецепту
    comments = recipe.comments_set.all()
    # Передаем контекст в шаблон
    return render(request, 'cooking_recipes/recipe.html', {'recipe': recipe, 'form': form, 'comments': comments})

webrecipes/user/views.py
from django.contrib.auth.views import LoginView
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views.generic import CreateView
from django.contrib.auth import login, logout

from .forms import LoginUserForm, RegisterUserForm
from .models import User


class RegisterUser(CreateView):
    def get(self, request):
        return render(request, 'cooking_recipes/register.html')

    def post(self, request):
        form = RegisterUserForm(request.POST)
        username = request.POST["username"]
        email = request.POST["email"]
        password = request.POST["password"]

        is_admin = request.POST.get("is_admin", False)
        # is_admin = request.POST["is_admin"]
        user = User.objects.create_user(username=username, email=email, password=password, is_admin=is_admin)
        form = RegisterUserForm(request.POST)

        return redirect('user:login')

    # def post(self, request):
    #     form = RegisterUserForm(request.POST)
    #     if form.is_valid():
    #         username = form.cleaned_data["username"]
    #         email = form.cleaned_data["email"]
    #         password = form.cleaned_data["password"]
    #         is_admin = form.cleaned_data["is_admin"]
    #         user = User.objects.create_user(username=username, email=email, password=password, is_admin=is_admin)
    #         return redirect('user:login')
    #     else:
    #         return render(request, 'cooking_recipes/register.html', {'form': form})


class LoginUser(LoginView):
    form_class = LoginUserForm
    template_name = 'cooking_recipes/login.html'

    def get_success_url(self):
        return reverse_lazy('home')


def logout_user(request):
    logout(request)
    return redirect('user:login')

webrecipes/user/templates/cooking_recipes/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock title%}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css">
    <link type="text/css" href="{% static 'cooking_recipes/css/styles.css' %}" rel="stylesheet"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <div class="d-flex justify-content-between d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white">
        <h5 class="my-0 mr-md-auto front-weight-normal">culMaster</h5>
        <nav class="my-2 my-md-0 mr-md-3">
            <a class="p-2 text-dark" href="{% url 'home' %}">Главная</a>
            <a class="p-2 text-dark" href="{% url 'about' %}">О нас</a>
        </nav>
        <a class="btn btn-outline-primary" href="{% url 'login' %}">Войти</a>

    </div>
</head>
<body>
<div class="container">
    {% block content %}
    {% endblock content%}
</div>
</body>
</html>

webrecipes/user/templates/cooking_recipes/login.html
{% extends 'cooking_recipes/base.html' %}

{% block title %}
Вход
{% endblock title %}

{% block content %}
<div class="login-form">
  <form method="POST" action="{% url 'user:login' %}">
    {% csrf_token %}
    <div class="form-group">
      <label for="username"><i class="fa fa-user"></i> Логин:</label>
      <input type="text" class="form-control" id="username" name="username" required>
    </div>
    <div class="form-group">
  <label for="password"><i class="fa fa-lock"></i> Пароль:</label>
  <div class="input-group">
    <input type="password" class="form-control" id="password" name="password" required>
    <button type="button" class="btn btn-outline-secondary password-toggle"><i class="fa fa-eye"></i></button>
  </div>
</div>

<!--Скрыпт для рэалізацыі кнопкі прагляду пароля карыстальніка-->
<script>
  const passwordInput = document.getElementById('password');
  const passwordToggle = document.querySelector('.password-toggle');

  passwordToggle.addEventListener('click', function() {
    if (passwordInput.type === 'password') {
      passwordInput.type = 'text';
      passwordToggle.innerHTML = '<i class="fa fa-eye-slash"></i>';
    } else {
      passwordInput.type = 'password';
      passwordToggle.innerHTML = '<i class="fa fa-eye"></i>';
    }
  });
</script>
    <button type="submit" class="btn btn-primary"><i class="fa fa-sign-in"></i> Войти</button>
      <p>Ещё не зарегистрировались? <a href="{% url 'user:register' %}">Нажмите сюда, чтобы зарегистрироваться.</a></p>
  </form>
</div>
{% endblock content %}

webrecipes/user/templates/cooking_recipes/register.html
{% extends 'cooking_recipes/base.html' %}

{% block title %}
Регистрация
{% endblock title %}

{% block content %}
<div class="login-form">
  <form method="POST" action="{% url 'user:register' %}">
    {% csrf_token %}
    <div class="form-group">
      <label for="username"><i class="fa fa-user"></i> Логин:</label>
      <input type="text" class="form-control" id="username" name="username" required>
    </div>

    <div class="form-group">
        <label for="email"><i class="fa fa-user"></i> Эл. Почта:</label>
        <input type="text" class="form-control" id="email" name="email" required>
    </div>

    <div class="form-group">
        <label for="password"><i class="fa fa-lock"></i> Пароль:</label>
        <div class="input-group">
        <input type="password" class="form-control" id="password" name="password" required>
        <button type="button" class="btn btn-outline-secondary password-toggle"><i class="fa fa-eye"></i></button>
  </div>
</div>

<!--Скрыпт для рэалізацыі кнопкі прагляду пароля карыстальніка-->
<script>
  const passwordInput = document.getElementById('password');
  const passwordToggle = document.querySelector('.password-toggle');

  passwordToggle.addEventListener('click', function() {
    if (passwordInput.type === 'password') {
      passwordInput.type = 'text';
      passwordToggle.innerHTML = '<i class="fa fa-eye-slash"></i>';
    } else {
      passwordInput.type = 'password';
      passwordToggle.innerHTML = '<i class="fa fa-eye"></i>';
    }
  });
</script>

      <div class="form-group">
            <label for="user-type"><i class="fa fa-check"></i> Зарегистрироваться как:</label>
            <input type="checkbox" id="admin-type" name="is_admin" value="admin"> Администратор
      </div>

    <button type="submit" class="btn btn-primary"><i class="fa fa-sign-in"></i> Зарегистрироваться</button>
  </form>
</div>
{% endblock content %}